"""Experiment tracking: a cumulative log + leaderboard + training curves, so
progress over time is visible across runs (not just the latest snapshot).

  record(name, metrics, ...)  -> appends a timestamped row to results/log.csv
                                 and regenerates results/leaderboard.md
  save_history(history, name) -> results/history_<name>.json + a train-vs-val
                                 loss curve PNG (also the overfitting evidence)
"""

from __future__ import annotations

import csv
import json
import os
from datetime import datetime

RESULTS_DIR = "results"
LOG = f"{RESULTS_DIR}/log.csv"
FIELDS = ["date", "experiment", "config", "HR@10", "MRR", "NDCG@10", "notes"]


def _fmt(v) -> str:
    try:
        return f"{float(v):.4f}"
    except (TypeError, ValueError):
        return ""


def record(experiment: str, metrics: dict, config: str = "", notes: str = "",
           date: str | None = None) -> dict:
    os.makedirs(RESULTS_DIR, exist_ok=True)
    row = {
        "date": date or datetime.now().strftime("%Y-%m-%d %H:%M"),
        "experiment": experiment, "config": config,
        "HR@10": _fmt(metrics.get("HR@10")), "MRR": _fmt(metrics.get("MRR")),
        "NDCG@10": _fmt(metrics.get("NDCG@10")), "notes": notes,
    }
    exists = os.path.exists(LOG)
    with open(LOG, "a", newline="") as fh:
        w = csv.DictWriter(fh, FIELDS)
        if not exists:
            w.writeheader()
        w.writerow(row)
    build_leaderboard()
    return row


def build_leaderboard() -> None:
    """Regenerate results/leaderboard.md from the cumulative log."""
    if not os.path.exists(LOG):
        return
    rows = list(csv.DictReader(open(LOG, encoding="utf-8", errors="replace")))
    out = [
        "# Reverie — Experiment Progress Log",
        "",
        "Chronological record of every run, so progress over time is visible.",
        "Auto-generated by `src/track.py`; newest at the bottom.",
        "",
        "| Date | Experiment | Config | HR@10 | MRR | NDCG@10 | Notes |",
        "| ---- | ---------- | ------ | ----- | --- | ------- | ----- |",
    ]
    for r in rows:
        out.append(f"| {r['date']} | {r['experiment']} | {r['config']} | "
                   f"{r['HR@10']} | {r['MRR']} | {r['NDCG@10']} | {r['notes']} |")
    valid = [r for r in rows if r["HR@10"]]
    if valid:
        best = max(valid, key=lambda r: float(r["HR@10"]))
        out += ["", f"**Best HR@10 so far:** {best['HR@10']} "
                    f"({best['experiment']}, {best['config']}, {best['date']})"]
    open(f"{RESULTS_DIR}/leaderboard.md", "w").write("\n".join(out) + "\n")


def save_history(history, name: str) -> None:
    """Persist Keras history + a train-vs-val loss curve (overfitting evidence)."""
    os.makedirs(RESULTS_DIR, exist_ok=True)
    h = history.history if hasattr(history, "history") else history
    json.dump(h, open(f"{RESULTS_DIR}/history_{name}.json", "w"))
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        plt.figure(figsize=(6, 4))
        if "loss" in h:
            plt.plot(h["loss"], label="train loss")
        if "val_loss" in h:
            plt.plot(h["val_loss"], label="val loss")
        plt.xlabel("epoch"); plt.ylabel("loss"); plt.legend()
        plt.title(f"{name}: train vs val loss")
        plt.tight_layout()
        plt.savefig(f"{RESULTS_DIR}/curve_{name}.png", dpi=120)
        plt.close()
    except Exception as exc:  # plotting is best-effort
        print("curve plot skipped:", exc)
